---
sudo: required

language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

# command to install dependencies
install:
    - pip install -r requirements_dev.txt

# command to run tests
script:
    - python -m unittest discover -s tests -f -v
    - python -m rlog_generator.cli -v
    - python -m rlog_generator.cli -h

after_success:
    - coveralls

notifications:
    email: false