---
dist: xenial
sudo: required
language: python
python:
    - "3.6"
    - "3.7"
    - "3.7-dev"
    - "3.8-dev"
    - "nightly"

# command to install dependencies
install:
    - pip install -r requirements_dev.txt
    - pip install coveralls

# command to run tests
script:
    - python -m unittest discover -s tests -f -v
    - python -m rlog_generator.cli --version
    - python -m rlog_generator.cli --help

after_success:
    - coveralls

notifications:
    email: false